# Site settings
title: Lukiomatematiikan kertauskurssi
email: henri.ruoho@helsinki.fi
description: > 
  T채m채 sivu on olemassa voidakseni tarjota kurssin teht채v채t nykyaikaisessa muodossa.

baseurl: "/lumake" # the subpath of your site, e.g. /blog/
url: "http://hruoho.github.io" # the base hostname & protocol for your site
github_username:  hruoho

# Build settings
markdown: kramdown
sass:
  sass_dir: bower_components/foundation/scss #"_sass/foundation/bower_components/foundation/scss"

exclude: [bower_components/MathJax]