# Site settings
title: Lukiomatematiikan kertauskurssi
email: henri.ruoho@helsinki.fi
description: > 
  T채m채 sivu on olemassa voidakseni tarjota kurssin teht채v채t nykyaikaisessa muodossa.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  hruoho

# Build settings
markdown: kramdown
